
sudo: required

language: cpp

os:
    - linux

compiler:
    - g++

addons:
    apt:
        packages:
            - libgtest-dev
            - wget

branches:
    only:
        - master

before_script:
    - g++ --version
    - .travis/install_dep.sh

script:
    - make

