
sudo: required

language: cpp

os:
    - linux

compiler:
    - g++

addons:
    apt:
        packages:
            - libgtest-dev
            - cmake

branches:
    only:
        - master

before_script:
    - g++ --version
    - mkdir build_gtest
    - cd build_gtest
    - cmake  /usr/src/gtest/CMakeLists.txt
    - make
    - cp libgtest*.a /usr/local/lib
    - cd -

script:
    - make

