
sudo: required

language: cpp

os:
    - linux

compiler:
    - g++

addons:
    apt:
        packages:
            - libgtest-dev
            - wget

branches:
    only:
        - master

before_script:
    - g++ --version
      #- chmod a+x ./.travis/install_dep.sh
      #- .travis/install_dep.sh
    - currtent_path=`pwd`
    - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - tar -xzv -f release-1.8.0.tar.gz
    - cd googletest-release-1.8.0
    - cd googletest/make/
    - make
    - ar rcs libgtest.a gtest-all.o
    - sudo cp libgtest.a /lib/
    - cd $currtent_path

script:
    - make clean
    - make

