
sudo: required

language: cpp

os:
    - linux

compiler:
    - g++

addons:
    apt:
        packages:
            libgtest-dev

branches:
    only:
        - master

before_install:
    - g++ --version

script:
    - make -j2

