
sudo: required

language: cpp

os:
    - linux

compiler:
    - g++

addons:
    apt:
        packages:
            - libgtest-dev
            - wget

branches:
    only:
        - master

before_script:
    - g++ --version
    - chmod a+x ./.travis/install_dep.sh
    - .travis/install_dep.sh
    - ls -l /usr/local/lib/libgtest.a

script:
    - make

